/**
 * Generated by create-universal-app. Describes which wrapper plugins were applied,
 * so a future `wrapper sync` can re-apply them after a plugin version bump.
 */
export default {
  "name": "tutorsOS",
  "platform": "web-nextjs",
  "plugins": {
    "seo": true,
    "auth": "none",
    "observability": "none",
    "deploy": "vercel",
    "sigmap": "full"
  }
} as const;
